- name: Gather facts about all Server Profiles
  oneview_server_profile_facts:
    config: "{{ config }}"
  delegate_to: localhost

- debug: var=server_profiles

- name: Gather facts about a Server Profile by name
  oneview_server_profile_facts:
    config: "{{ config }}"
    name: "server profile name"
  delegate_to: localhost

- debug: var=server_profiles
