- name: Create a Storage Volume Template
  oneview_storage_volume_template:
    config: "{{ config }}"
    state: present
    data:
        name: 'Ansible Volume Creation'
        state: "Configured"
        description: "Using Ansible code to create a volume"
        provisioning:
             shareable: true
             provisionType: "Thin"
             capacity: "{{ c20Gb }}"
             storagePoolUri: "{{ Vol_Stor_Pool1_Uri }}"
        stateReason: "None"
        storageSystemUri: "{{ Vol_Stor_Sys }}"
        snapshotPoolUri: "{{ Vol_Stor_Pool1_Uri }}"
        type: StorageVolumeTemplateV3
  delegate_to: localhost