- name: Create Ethernet networks in bulk
  oneview_ethernet_network:
    config: "{{ config }}"
    state: present
    data:
      vlanIdRange: '10,11,12'
      purpose: General
      namePrefix: AnsibleSynTest
      smartLink: false
      privateNetwork: false
      bandwidth:
        maximumBandwidth: 20000
        typicalBandwidth: 2500