- name: Ensure that the Logical Interconnect Group is present
  oneview_logical_interconnect_group:
    config: "{{ config }}"
    state: present
    data:
      name: 'Test Logical Interconnect Group'
      enclosureIndexes: [1]
      enclosureType: "{{ Encl_Type }}"
      interconnectBaySet: 3
      redundancyType: "Redundant"
#
# Now for the interconnect connections
#
      interconnectMapTemplate:
        interconnectMapEntryTemplates:
          - logicalDownlinkUri: ~
            logicalLocation:
                locationEntries:
                    - relativeValue: 3
                      type: "Bay"
                    - relativeValue: 1
                      type: "Enclosure"
            permittedInterconnectTypeName: "{{ InterconType40 }}"
          - logicalDownlinkUri: ~
            logicalLocation:
                locationEntries:
                    - relativeValue: 6
                      type: "Bay"
                    - relativeValue: 1
                      type: "Enclosure"
            permittedInterconnectTypeName: "{{ InterconType40 }}"
#
# This is the Uplink Set code. Everytime logical Port Config Infos appears, its a new uplink. For visual aid, a single '#' will be used to break up the code
#
      uplinkSets:
        - logicalPortConfigInfos:
          - desiredSpeed: "Auto"
            logicalLocation:
                  locationEntries:
                    - relativeValue: 6
                      type: "Bay"
                    - relativeValue: "{{ Port_Q1:1 }}"
                      type: "Port"
                    - relativeValue: 1
                      type: "Enclosure"
          - desiredSpeed: "Auto"
            logicalLocation:
                  locationEntries:
                    - relativeValue: 6
                      type: "Bay"
                    - relativeValue: "{{ Port_Q2:1 }}"
                      type: "Port"
                    - relativeValue: 1
                      type: "Enclosure"
          name: "SAN-B-UplinkSet"
          mode: "Auto"
          networkType: "FibreChannel" #Ethernet is the other option
          networkUris:
            - "{{ NET_SAN_B_Uri }}"
#
        - logicalPortConfigInfos:
          - desiredSpeed: "Auto"
            logicalLocation:
                  locationEntries:
                    - relativeValue: 3
                      type: "Bay"
                    - relativeValue: "{{ Port_Q2:1 }}"
                      type: "Port"
                    - relativeValue: 1
                      type: "Enclosure"
          - desiredSpeed: "Auto"
            logicalLocation:
                  locationEntries:
                    - relativeValue: 3
                      type: "Bay"
                    - relativeValue: "{{ Port_Q1:1 }}"
                      type: "Port"
                    - relativeValue: 1
                      type: "Enclosure"
          name: "SAN-A-UplinkSet"
          mode: "Auto"
          networkType: "FibreChannel" #Ethernet / FibreChannel are the options
          networkUris:
            - "{{ NET_SAN_A_Uri }}"
#
        - logicalPortConfigInfos:
          - desiredSpeed: "Auto"
            logicalLocation:
                  locationEntries:
                    - relativeValue: 3
                      type: "Bay"
                    - relativeValue: "{{ Port_Eth_FCoE_Q1:1 }}" #Ethernet + FCoE Capability
                      type: "Port"
                    - relativeValue: 1
                      type: "Enclosure"
          name: "Deployment-Uplink"
          mode: "Auto"
          networkType: "Ethernet" #Ethernet / FibreChannel are the options
          networkUris:
            - "{{ NET_Deploy_Uri }}"
#
        - logicalPortConfigInfos:
          - desiredSpeed: "Auto"
            logicalLocation:
                  locationEntries:
                    - relativeValue: 6
                      type: "Bay"
                    - relativeValue: "{{ Port_Eth_FCoE_Q3:1 }}" #Ethernet + FCoE Capability
                      type: "Port"
                    - relativeValue: 1
                      type: "Enclosure"
          - desiredSpeed: "Auto"
            logicalLocation:
                  locationEntries:
                    - relativeValue: 6
                      type: "Bay"
                    - relativeValue: "{{ Port_Eth_FCoE_Q4:1 }}" #Ethernet + FCoE Capability
                      type: "Port"
                    - relativeValue: 1
                      type: "Enclosure"
          - desiredSpeed: "Auto"
            logicalLocation:
                  locationEntries:
                    - relativeValue: 3
                      type: "Bay"
                    - relativeValue: "{{ Port_Eth_FCoE_Q3:1 }}" #Ethernet + FCoE Capability
                      type: "Port"
                    - relativeValue: 1
                      type: "Enclosure"
          - desiredSpeed: "Auto"
            logicalLocation:
                  locationEntries:
                    - relativeValue: 3
                      type: "Bay"
                    - relativeValue: "{{ Port_Eth_FCoE_Q4:1 }}" #Ethernet + FCoE Capability
                      type: "Port"
                    - relativeValue: 1
                      type: "Enclosure"                                                                  
          name: "LAN-UplinkSet"
          mode: "Auto"
          networkType: "Ethernet" #Ethernet / FibreChannel are the options
          networkUris:
            - "{{ NET_VLANDMZ_Uri }}"
            - "{{ NET_VLANMan_Uri }}"
            - "{{ NET_VLANCust_Uri }}"