- name: Power Off the server hardware
  oneview_server_hardware:
    config: "{{ config }}"
    state: power_state_set
    data:
        name : "{{ Serv_b5 }}" #Choose a bay to turn off
        powerStateData:
            powerState: "Off"
            powerControl: "PressAndHold" #MomentaryPress and PressAndHold are the two options
  delegate_to: localhost
